apiVersion: v1

kind: PersistentVolume

metadata:
  name: wp-pv
  labels:
    app: wordpress

spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/wp"
